/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Abi } from "./ERC20Abi";
export * as factories from "./factories";
export { ERC20Abi__factory } from "./factories/ERC20Abi__factory";
